// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';


function handler(_, _$1, callback) {
  return callback(null, "Hello world!");
}

exports.handler = handler;
/* No side effect */
